version: "3.1"
services: 
  unturned:
    user: 1000:1000
    build: ./build/
    volumes:
      - ./data:/srv/unturned
    environment: 
      - ID=user
      - PASS=pass
      - INSTANCE=svrname
    ports: 
      - "27015:27015/udp"
      - "27016:27016/udp"
      - "27017:27017/udp"