version: "3.1"
services:
  unturned:
    build: ./build/
    volumes:
      - ./data/unturned:/srv/unturned
    environment:
      - ID=user
      - PASS=pass
      - INSTANCE=svrname
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
      - "27017:27017/udp"
  mariadb:
    image: mariadb:latest
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: unturned